### ISSUE TITLE
UX: placing formulas by dragging a contiguous path on the canvas

### ISSUE THREAD

**Issue by guiltygyoza** [topology-gg/mumu-view#101]
sort of like deploying Wires and Belts in Isaac. @zinkkrysty what do you think?

**Comment by guiltygyoza** [comment]
the high level idea is to have the editor UX slowly depart from "programming / configuring texts" to "waving wands to craft magic spells / alchemy circles"

**Comment by zinkkrysty** [comment]
👍 Yes, point and click is much better! 

However drag can sometimes be a bit fiddly so I suggest the following flow:

1. Click on "add formula".
2. Choose formula type
3. You can now click on the board to place operand 1
4. Click on the board to place operand 2
5. ... repeat 3 and 4 until we're done
6. Invalid placements of operands (non-adjacent positions) will not let you continue
7. when last operand is placed, if formula is "valid" then formula is "finished"
8. You can always click and reposition/drag the operands to modify a formula

It will take some time to achieve this, but we can perhaps do this in stages. We can do 1 through 7 and leave out 8 for simplicity.
