### ISSUE TITLE
UI: visually bundle operator editor and mech programming into a "Diagram Editor" panel

### ISSUE THREAD

**Issue by guiltygyoza** [topology-gg/mumu-view#90]
to reinforce the idea that players are inventing diagrams using alchemical physics of the MuMu universe

**Comment by zinkkrysty** [comment]
An idea for organizing the panels/content:

* The programming part occupies the lower half of the screen - and is scrollable inside
* Operator & mech programming are under collapsible panels (accordion style)
* Board is always visible (play controls can be moved somewhere else and have more efficient use of space)

![image](https://user-images.githubusercontent.com/570771/201745721-d3b83ce7-d957-49b3-a268-c27b53577e0a.png)
